<?php
/**
 * The only way an uploaded document leaves the server. Checks who is asking
 * before it sends a byte: a client may read their own files, an admin may read
 * any. The storage folder itself is closed to the web.
 */

declare(strict_types=1);

require_once __DIR__ . '/lib/auth.php';
require_once __DIR__ . '/lib/files.php';

$user = require_user();
$id   = (int) ($_GET['id'] ?? 0);

$stmt = db()->prepare('SELECT * FROM portal_files WHERE id = ?');
$stmt->execute([$id]);
$file = $stmt->fetch();

if (!$file || ($user['role'] !== 'admin' && (int) $file['client_id'] !== (int) $user['id'])) {
    http_response_code(404);
    exit('Not found.');
}

// stored_name is generated by us, but never build a path from input without
// checking it cannot climb out of the folder.
$name = basename((string) $file['stored_name']);
$path = storage_dir() . '/' . $name;
if (!is_file($path)) {
    http_response_code(404);
    exit('That file is no longer on the server.');
}

$download = preg_replace('/[^A-Za-z0-9 ._-]/', '_', (string) $file['original_name']) ?: 'document';

header('Content-Type: ' . ($file['mime'] ?: 'application/octet-stream'));
header('Content-Disposition: attachment; filename="' . $download . '"');
header('Content-Length: ' . (string) filesize($path));
header('X-Content-Type-Options: nosniff');
header('Cache-Control: private, no-store');
readfile($path);
